### ISSUE TITLE
Remove / amend non-Wikipedia entries into the skills graph 

### ISSUE THREAD

**Issue by Josh-Woodcock** [UoMResearchIT/RSESkillsGraph#43] opened 2023-10-11 15:02 UTC
As per [Mike's findings](https://teams.microsoft.com/l/message/19:e37ef6879ac34b0f83fd2cfe9e3117d6@thread.tacv2/1697025033588?tenantId=c152cb07-614e-4abb-818a-f035cfa91a77&groupId=22c918a5-7504-4d24-9623-d592a54bc139&parentMessageId=1697025033588&teamName=Research%20IT&channelName=Random&createdTime=1697025033588&allowXTenantAccess=false) there are items in the RSE Skills graph that do not have a Wikipedia main artile heading.

Should these be removed / amended or should there be a different policy on what gets included ?

There are also some with spelling variations, does this affect the functionality of the skills graph ? e.g if there is a typo does that stop it being linked with the correct spelling ?

**Comment by ianhinder** [comment] 2023-10-12 13:01
Hi Josh, sorry - only just saw this!  Yes, we should amend these.  See https://github.com/UoMResearchIT/RSESkillsGraph/issues/50.  I have also added a test for this that is shown in each PR.  We should probably add a list of extra topics which are not wikipedia entries that we want to have.

If there is a typo, it would just appear as an additional entry.  When you click on a topic, the code seems to ask wikipedia for the first 40 results for a search for that topic name, and takes those as the "related" topics to show in the graph.  If someone has a typo in their topic name, then they will not show up in this graph.

**Comment by ianhinder** [comment] 2023-11-03 10:29
Duplicate of #50.

**Closed by ianhinder** 2023-11-03 10:29 UTC
Labels: bug, question
